STAGES = {"PRELIMS", "MAINS"}
VERIFICATION = {"VERIFIED", "PARTIALLY_VERIFIED", "UNVERIFIED", "CONFLICTING_SOURCE", "MISSING_SOURCE"}
SOURCE_TYPES = {"OFFICIAL", "SECONDARY_SOURCE", "QUESTION_ARCHIVE", "USER_PROVIDED", "AI_GENERATED", "UNVERIFIED"}
DIFFICULTIES = {"EASY", "MODERATE", "HARD", "UNCERTAIN"}
TIME_REQUIREMENTS = {"VERY_FAST", "FAST", "MODERATE", "TIME_CONSUMING", "UNCERTAIN"}
TREND_VALUES = {"INCREASING", "STABLE", "DECREASING", "EMERGING", "INSUFFICIENT_DATA"}
PRIORITIES = {"P0", "P1", "P2", "P3", "P4", "UNRANKED"}
REAL_STATUSES = {"VERIFIED", "PARTIALLY_VERIFIED", "CONFLICTING_SOURCE"}
