STAGES = {"PRELIMS", "MAINS", "UNKNOWN_STAGE"}
VERIFICATION = {"VERIFIED", "PARTIALLY_VERIFIED", "UNVERIFIED", "CONFLICTING_SOURCE", "MISSING_SOURCE"}
COMPLETENESS = {"COMPLETE", "PARTIAL", "MISSING_SOURCE", "UNVERIFIED", "CONFLICTING_SOURCE"}
PAPER_ACCESS = {"SOURCE_LEAD", "PAPER_FOUND", "VERIFIED"}
SOURCE_TYPES = {"OFFICIAL", "REPUTABLE_EDUCATIONAL", "QUESTION_ARCHIVE", "USER_PROVIDED", "OTHER"}
TEXT_CERTAINTY = {"CERTAIN", "TEXT_UNCERTAIN"}
